version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
    target-branch: "master"
    open-pull-requests-limit: 10

  - package-ecosystem: "cargo"
    directory: "/app/src-tauri"
    schedule:
      interval: "weekly"
    target-branch: "master"
    open-pull-requests-limit: 10
